import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
padding = { x = 14, y = 10}
dynamic_padding = true
opacity = 0.9
dimensions = { lines = 24, columns = 80 }
dynamic_title = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
size = 14

[colors]

